-- =====================================================
-- AcadPulse PostgreSQL Schema
-- Supabase Compatible
-- =====================================================

-- Required Extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =====================================================
-- 1. USERS
-- =====================================================
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name TEXT NOT NULL,
    email TEXT UNIQUE,
    password_hash TEXT,
    whatsapp_number TEXT,
    gmail_connected BOOLEAN NOT NULL DEFAULT FALSE,
    classroom_connected BOOLEAN NOT NULL DEFAULT FALSE,
    whatsapp_connected BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================================================
-- 2. COURSES
-- =====================================================
CREATE TABLE courses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    course_code TEXT NOT NULL,
    course_name TEXT NOT NULL
);

-- =====================================================
-- 3. COURSE ALIASES
-- =====================================================
CREATE TABLE course_aliases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    alias TEXT NOT NULL,
    UNIQUE(course_id, alias)
);

-- =====================================================
-- 4. USER COURSES
-- =====================================================
CREATE TABLE user_courses (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    professor_name TEXT,
    PRIMARY KEY (user_id, course_id)
);

-- =====================================================
-- 5. WHATSAPP GROUPS
-- =====================================================
CREATE TABLE whatsapp_groups (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    whatsapp_group_id TEXT UNIQUE NOT NULL,
    group_name TEXT NOT NULL,
    is_general BOOLEAN NOT NULL DEFAULT FALSE
);

-- =====================================================
-- 6. USER WHATSAPP GROUPS
-- =====================================================
CREATE TABLE user_whatsapp_groups (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    whatsapp_group_id UUID NOT NULL REFERENCES whatsapp_groups(id) ON DELETE CASCADE,
    is_selected BOOLEAN NOT NULL DEFAULT TRUE,
    is_ignored BOOLEAN NOT NULL DEFAULT FALSE,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, whatsapp_group_id)
);

-- =====================================================
-- 7. CLASSROOM COURSES
-- =====================================================
CREATE TABLE classroom_courses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    classroom_id TEXT UNIQUE NOT NULL,
    classroom_name TEXT NOT NULL
);

-- =====================================================
-- 8. USER CLASSROOM COURSES
-- =====================================================
CREATE TABLE user_classroom_courses (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    classroom_course_id UUID NOT NULL REFERENCES classroom_courses(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, classroom_course_id)
);

-- =====================================================
-- 9. COURSE SOURCE MAPPINGS
-- =====================================================
CREATE TABLE course_source_mappings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    source_type TEXT NOT NULL CHECK (
        source_type IN ('whatsapp', 'gmail', 'classroom')
    ),
    source_reference_id TEXT NOT NULL
    -- Examples:
    -- WhatsApp  : '120363418273@g.us'
    -- Classroom : '684219537821'
    -- Gmail     : 'professor@university.edu'
);

-- =====================================================
-- 10. NOTIFICATIONS
-- =====================================================
CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Unique notification ID generated by PostgreSQL.

    user_id UUID NOT NULL
        REFERENCES users(id) ON DELETE CASCADE,
    -- Owner of this notification.
    -- If the user is deleted, all their notifications are deleted too.

    course_id UUID
        REFERENCES courses(id) ON DELETE SET NULL,
    -- Related course.
    -- Can be NULL for general announcements or uncategorized messages.

    source_type TEXT NOT NULL
        CHECK (
            source_type IN (
                'whatsapp',
                'gmail',
                'classroom',
                'manual'
            )
        ),
    -- Where this notification came from.

    source_reference_id TEXT,
    -- Source identifier.
    --
    -- WhatsApp  : Group ID
    -- Gmail     : Sender email
    -- Classroom : Classroom ID
    -- Manual    : NULL

    external_message_id TEXT,
    -- Original platform message ID.
    --
    -- WhatsApp  : message.key.id
    -- Gmail     : Gmail message ID
    -- Classroom : announcement/coursework ID
    -- Manual    : NULL

    sender_name TEXT,
    -- Human-readable sender name.
    -- Example: "Dr. Ahmed", "CS Department".

    message_text TEXT NOT NULL,
    -- Full cleaned notification content.

    category TEXT NOT NULL
        CHECK (
            category IN (
                'assignment',
                'quiz',
                'announcement',
                'material',
                'event',
                'exam_schedule',
                'noise'
            )
        ),
    -- Notification classification.

    deadline TIMESTAMPTZ,
    -- Extracted deadline, if any.

    urgency_score INTEGER NOT NULL DEFAULT 0,
    -- Numeric urgency score: 0 none, 1 low, 2 medium, 3 high, 4 critical, 5 overdue.

    urgency_label TEXT NOT NULL DEFAULT 'none'
        CHECK (
            urgency_label IN (
                'none',
                'low',
                'medium',
                'high',
                'critical',
                'overdue'
            )
        ),
    -- Calculated urgency label used by the frontend.

    urgency_level TEXT
        CHECK (
            urgency_level IN (
                'low',
                'medium',
                'high',
                'critical',
                'overdue'
            )
        ),
    -- Calculated urgency.

    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    -- Whether the student has completed the task.

    received_at TIMESTAMPTZ NOT NULL,
    -- When the original source generated the message.

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- When AcadPulse stored this notification.

    CONSTRAINT chk_notification_source_fields
    CHECK (
        (
            source_type = 'manual'
            AND source_reference_id IS NULL
            AND external_message_id IS NULL
        )
        OR
        (
            source_type IN ('whatsapp', 'gmail', 'classroom')
            AND source_reference_id IS NOT NULL
            AND external_message_id IS NOT NULL
        )
    )
);

-- Prevent duplicate notifications
CREATE UNIQUE INDEX idx_notifications_unique_source_message
ON notifications(user_id, source_type, external_message_id);

-- =====================================================
-- 11. TIMETABLE ENTRIES
-- =====================================================
CREATE TABLE timetable_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,

    day_of_week INTEGER NOT NULL CHECK (
        day_of_week BETWEEN 1 AND 7
    ),

    start_time TIME NOT NULL,
    end_time TIME NOT NULL,

    room_number TEXT
);

-- =====================================================
-- 12. ATTACHMENTS
-- =====================================================
CREATE TABLE attachments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    notification_id UUID NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_type TEXT NOT NULL
);

-- =====================================================
-- PERFORMANCE INDEXES
-- =====================================================
CREATE INDEX idx_notifications_user_received
ON notifications(user_id, received_at DESC);

CREATE INDEX idx_notifications_course_deadline
ON notifications(course_id, deadline);

CREATE INDEX idx_course_source_lookup
ON course_source_mappings(user_id, source_type, source_reference_id);

CREATE INDEX idx_timetable_user_day
ON timetable_entries(user_id, day_of_week, start_time);
